# Generated by Django 2.2.6 on 2019-10-16 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 16, 18, 30, 15, 947942)),
        ),
    ]
