# Generated by Django 2.2.6 on 2019-10-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
    ]
