# Generated by Django 2.2.6 on 2019-10-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name_category',
        ),
    ]
