# Generated by Django 2.2.6 on 2019-10-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Електроніка', 'Електроніка')], default='Електроніка', max_length=100),
        ),
    ]
