# Generated by Django 2.2.6 on 2019-10-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20191017_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Електроніка', 'Електроніка'), ('status', 'status')], default='Електроніка', max_length=100),
        ),
    ]
