# Generated by Django 2.2.6 on 2019-10-17 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20191017_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Компьютеры и ноутбуки', 'Компьютеры и ноутбуки')], default='Компьютеры и ноутбуки', max_length=100),
        ),
    ]
