# Generated by Django 2.2.6 on 2019-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191017_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Компьютеры и ноутбуки', 'Компьютеры и ноутбуки'), ('s ', 's '), ('d', 'd'), ('q', 'q'), (' gd', ' gd')], default='Компьютеры и ноутбуки', max_length=100),
        ),
    ]
