# Generated by Django 2.2.6 on 2019-10-28 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_undercategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Undercategory',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
