# Generated by Django 2.2.6 on 2019-10-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20191029_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_product',
            field=models.CharField(max_length=200),
        ),
    ]
